default_button: true
default_message: true
default_tab: true
default_tab_edit: true
_core:
  default_config_hash: ffjwyOkkEGJcHRBGwLlGLtdWUcTvXx8Dclcq43MZrT8
button:
  guide: true
message:
  guide: true
tab:
  guide: true
tab_edit:
  guide: true
