default_button: true
default_message: true
default_tab: true
default_tab_edit: true
_core:
  default_config_hash: ffjwyOkkEGJcHRBGwLlGLtdWUcTvXx8Dclcq43MZrT8
button:
  guide: true
  card: false
  spag: false
  vdas: false
  vtyp: false
message:
  guide: true
  card: false
  spag: false
  vdas: false
  vtyp: false
tab:
  guide: true
  card: false
  spag: false
  vdas: false
  vtyp: false
tab_edit:
  guide: true
  card: false
  spag: false
  vdas: false
  vtyp: false
