definitions:
  user__page:
    weight: -47
    menu_name: account
    parent: ''
    expanded: false
    enabled: true
  user__logout:
    weight: -46
    menu_name: account
    parent: ''
    expanded: false
    enabled: true
  standard__front_page:
    enabled: false
    menu_name: main
    parent: ''
    expanded: false
    weight: 0
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
